// @ts-nocheck -- vendored drop-in; not authored against any consumer's strict/checkJs config.
/**
 * @fileoverview Zero-dependency test-coverage reporter for Node.js ESM apps, plus
 * the shared `/coverage` endpoint contract for the process-mgr fleet. Sibling of
 * sloc.js — same shape, same adapters (Express or SvelteKit/Fetch), same
 * config-discovery rules.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY A COMMITTED SNAPSHOT
 * ─────────────────────────────────────────────────────────────────────────────
 * Coverage only exists after tests run — and production deploys never run tests
 * (process-mgr's update does `install` + `build` only). So a `/coverage` endpoint
 * that reads `coverage/` alone reports "no data" in prod, forever.
 *
 * The fix: when you run coverage locally, a small `.coverage-snapshot.json` is
 * written next to your package and COMMITTED. It ships with the code and is what
 * prod serves. `coverage/` itself stays gitignored.
 *
 *   "test:coverage":     "<see RECIPES below>",
 *   "posttest:coverage": "node coverage.js --snapshot"
 *
 * The endpoint reads all three sources and uses whichever was generated most
 * recently, so your dev box shows live numbers and prod shows the snapshot:
 *
 *   1. coverage/coverage-summary.json   Istanbul json-summary (vitest, jest)
 *   2. coverage/lcov.info               lcov (node:test, and any runner's lcov)
 *   3. .coverage-snapshot.json          the committed snapshot (prod)
 *
 * Note (3) is compared by its recorded `generatedAt`, NOT its file mtime — a git
 * checkout rewrites mtimes and would otherwise make old coverage look brand new.
 *
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * SETUP
 * ─────────────────────────────────────────────────────────────────────────────
 * Copy this file to the project root, add the two npm scripts, wire two routes,
 * run coverage once, and commit the generated `.coverage-snapshot.json`.
 *
 * Express:
 *   import { createCoverageRoute, createCoverageDashboardRoute } from './coverage.js'
 *   app.get('/coverage',           createCoverageRoute(process.cwd(), { name: 'my-app' }))
 *   app.get('/coverage/dashboard', createCoverageDashboardRoute({ name: 'my-app' }))
 *
 * SvelteKit (one `+server.js` per route; adjust the relative depth):
 *   // src/routes/coverage/+server.js
 *   import { createCoverageHandler } from '../../../coverage.js'
 *   export const GET = createCoverageHandler(process.cwd(), { name: 'my-app' })
 *
 *   // src/routes/coverage/dashboard/+server.js
 *   import { createCoverageDashboardHandler } from '../../../../coverage.js'
 *   export const GET = createCoverageDashboardHandler({ name: 'my-app' })
 *
 * Mount `/coverage` ABOVE any catch-all / 404 / SPA fallback, exactly as with
 * `/sloc` — a wildcard registered first will silently shadow it.
 *
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * RECIPES — making your runner emit an artifact
 * ─────────────────────────────────────────────────────────────────────────────
 * node:test (no new dependencies — emits lcov natively). It will NOT create the
 * destination directory, hence the `pretest` hook (portable: no shell mkdir -p):
 *   "pretest:coverage":  "node coverage.js --ensure-dir",
 *   "test:coverage": "node --test --experimental-test-coverage
 *                     --test-reporter=lcov --test-reporter-destination=coverage/lcov.info
 *                     --test-reporter=spec --test-reporter-destination=stdout
 *                     src/tests/*.test.js",
 *   "posttest:coverage": "node coverage.js --snapshot"
 *
 * vitest — add 'json-summary' to the coverage reporter (needs @vitest/coverage-v8
 * or @vitest/coverage-istanbul):
 *   coverage: { provider: 'v8', reporter: ['text', 'html', 'json-summary'] }
 *   "test:coverage": "vitest run --coverage",
 *   "posttest:coverage": "node coverage.js --snapshot"
 *
 * jest:
 *   coverageReporters: ['text', 'lcov', 'json-summary']
 *   "posttest:coverage": "node coverage.js --snapshot"
 *
 * Then: `npm run test:coverage` && `git add .coverage-snapshot.json`.
 *
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * MULTI-PACKAGE REPOS — coverage.config.json
 * ─────────────────────────────────────────────────────────────────────────────
 * A repo whose tests live in several packages declares them, exactly like
 * sloc.config.json. Discovery walks UP from the dir being read and stops at the
 * repo boundary (the first dir containing .git), so any sub-server's `/coverage`
 * reports the WHOLE project.
 *
 *   // media-server/coverage.config.json
 *   { "roots": ["index-server", "cache-server", "svelte-ui", "audit-server"] }
 *
 * Each root keeps its own `coverage/` and its own `.coverage-snapshot.json`
 * (generated by that package's own posttest hook). Roots with no artifact report
 * `available:false` and are EXCLUDED from the weighted project total rather than
 * counted as 0% — a package with no tests shouldn't drag the number down; it
 * shows up as a gap instead. Single-package repos need no config.
 *
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * RESPONSE SHAPE — GET /coverage
 * ─────────────────────────────────────────────────────────────────────────────
 *   {
 *     "name": "my-app",
 *     "root": "/abs/project/root",   // the config's dir, or rootDir — dedupe key
 *     "available": true,
 *     "source": "snapshot",          // coverage-summary | lcov | snapshot | mixed
 *     "generatedAt": "2026-07-09T…", // OLDEST root's timestamp (honest staleness)
 *     "ageDays": 3.2,
 *     "stale": false,                // ageDays > staleAfterDays (default 14)
 *     "totals": {
 *       "lines":      { "total": 1620, "covered": 518, "pct": 31.97 },
 *       "statements": { … }, "functions": { … }, "branches": { … }
 *     },
 *     "roots": [ { "path": "index-server", "available": true, "source": "…",
 *                  "generatedAt": "…", "totals": { … } } ]
 *   }
 *
 * Project totals are WEIGHTED (Σcovered / Σtotal across roots), never a mean of
 * percentages. `?detail=true` additionally returns `files` — a map of
 * project-relative path → per-metric counts. It's opt-in because it's large and
 * process-mgr's fleet aggregator never needs it.
 *
 * An app that can't use this script just needs to return this JSON shape.
 *
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * LIMITATIONS
 * ─────────────────────────────────────────────────────────────────────────────
 * - lcov carries no `statements` metric. When reading lcov, `statements` is
 *   aliased to `lines`. Don't read across-runner statement deltas as meaningful.
 * - v8 and istanbul providers legitimately disagree on the same code. Percentages
 *   are comparable for one app over time, not strictly between apps.
 * - node:test's --experimental-test-coverage only reports files it actually
 *   LOADED during the run. A module no test ever imports is invisible, not 0% —
 *   so these percentages read optimistically high. Runners configured with an
 *   `include` glob (vitest/jest) count untested files as 0% and read lower.
 * - A failing suite exits non-zero, so npm skips `posttest:coverage` and no
 *   snapshot is written. That's deliberate: never publish coverage from a red run.
 * - `generatedAt` for a multi-root project is the OLDEST root's timestamp, so the
 *   number is never presented as fresher than its stalest part.
 * - Nothing here runs your tests. `createCoverageRunRoute` exists but is NOT
 *   wired by default and must never be exposed in production.
 */

import { readFile, writeFile, stat, readdir, mkdir } from 'node:fs/promises';
import { join, dirname, resolve, relative, sep, isAbsolute } from 'node:path';

const METRICS = ['lines', 'statements', 'functions', 'branches'];

export const SNAPSHOT_FILE = '.coverage-snapshot.json';
export const CONFIG_FILE = 'coverage.config.json';
export const DEFAULT_STALE_AFTER_DAYS = 14;

// ── Metric helpers ───────────────────────────────────────────────────────────

function pct(covered, total) {
    return total > 0 ? Math.round((covered / total) * 10000) / 100 : 0;
}

function emptyMetric() { return { total: 0, covered: 0, pct: 0 }; }

function emptyTotals() {
    const t = {};
    for (const m of METRICS) t[m] = emptyMetric();
    return t;
}

function normMetric(m) {
    const total = Number(m?.total) || 0;
    const covered = Number(m?.covered) || 0;
    return { total, covered, pct: pct(covered, total) };
}

function normTotals(t) {
    const out = emptyTotals();
    for (const m of METRICS) out[m] = normMetric(t?.[m]);
    return out;
}

function finalize(totals) {
    for (const m of METRICS) totals[m].pct = pct(totals[m].covered, totals[m].total);
    return totals;
}

/** Weighted accumulate: sums counts, never averages percentages. */
function addTotals(dst, src) {
    for (const m of METRICS) {
        dst[m].total += src?.[m]?.total ?? 0;
        dst[m].covered += src?.[m]?.covered ?? 0;
    }
    return dst;
}

// ── Path helpers ─────────────────────────────────────────────────────────────

function toPosix(p) { return String(p).split(sep).join('/').replace(/\\/g, '/'); }

/**
 * Istanbul summaries key files by ABSOLUTE authoring-machine paths
 * ("C:/dev/app/src/x.ts"). Store them project-relative so prod doesn't serve dev
 * paths and snapshot diffs stay stable across machines.
 */
function relPath(rootDir, filePath) {
    const p = toPosix(filePath);
    if (isAbsolute(p) || /^[A-Za-z]:\//.test(p)) {
        const r = relative(rootDir, p.replace(/\//g, sep));
        if (r && !r.startsWith('..')) return toPosix(r);
    }
    return p.replace(/^\.\//, '');
}

// ── Artifact parsers ─────────────────────────────────────────────────────────

/** Istanbul `coverage-summary.json`: { total: {...}, "<abs file>": {...} }. */
function fromIstanbulSummary(rootDir, data) {
    const totals = normTotals(data?.total);
    const files = {};
    for (const [key, value] of Object.entries(data ?? {})) {
        if (key === 'total' || !value || typeof value !== 'object' || !value.lines) continue;
        files[relPath(rootDir, key)] = normTotals(value);
    }
    return { totals, files };
}

/**
 * lcov: per-record LF/LH (lines), FNF/FNH (functions), BRF/BRH (branches).
 * There is no statements metric — it's aliased to lines.
 */
function fromLcov(rootDir, text) {
    const totals = emptyTotals();
    const files = {};
    let current = null;

    const flush = () => {
        if (!current) return;
        current.metrics.statements = { ...current.metrics.lines }; // lcov has no statements
        finalize(current.metrics);
        files[current.path] = current.metrics;
        addTotals(totals, current.metrics);
        current = null;
    };

    for (const raw of String(text).split('\n')) {
        const line = raw.trim();
        if (!line) continue;

        if (line.startsWith('SF:')) {
            flush();
            current = { path: relPath(rootDir, line.slice(3)), metrics: emptyTotals() };
            continue;
        }
        if (!current) continue;
        if (line === 'end_of_record') { flush(); continue; }

        const idx = line.indexOf(':');
        if (idx === -1) continue;
        const key = line.slice(0, idx);
        const num = Number(line.slice(idx + 1));
        if (!Number.isFinite(num)) continue;

        switch (key) {
            case 'LF':  current.metrics.lines.total = num; break;
            case 'LH':  current.metrics.lines.covered = num; break;
            case 'FNF': current.metrics.functions.total = num; break;
            case 'FNH': current.metrics.functions.covered = num; break;
            case 'BRF': current.metrics.branches.total = num; break;
            case 'BRH': current.metrics.branches.covered = num; break;
            default: break;
        }
    }
    flush();
    return { totals: finalize(totals), files };
}

// ── Artifact discovery (one package root) ────────────────────────────────────

async function readCandidate(rootDir, source, file) {
    let raw, st;
    try {
        st = await stat(file);
        raw = await readFile(file, 'utf-8');
    } catch {
        return null;
    }

    try {
        if (source === 'lcov') {
            const { totals, files } = fromLcov(rootDir, raw);
            if (totals.lines.total === 0) return null;
            return { source, generatedAt: new Date(st.mtimeMs).toISOString(), ts: st.mtimeMs, totals, files };
        }

        const data = JSON.parse(raw);

        if (source === 'coverage-summary') {
            const { totals, files } = fromIstanbulSummary(rootDir, data);
            return { source, generatedAt: new Date(st.mtimeMs).toISOString(), ts: st.mtimeMs, totals, files };
        }

        // snapshot: trust its recorded generatedAt — a git checkout rewrites mtime.
        const generatedAt = data?.generatedAt ?? new Date(st.mtimeMs).toISOString();
        const ts = Date.parse(generatedAt);
        return {
            source: 'snapshot',
            generatedAt,
            ts: Number.isFinite(ts) ? ts : st.mtimeMs,
            totals: finalize(normTotals(data?.totals)),
            files: data?.files ?? {},
        };
    } catch {
        return null; // malformed artifact — treat as absent rather than 500
    }
}

/** Read one package root, preferring whichever artifact was generated most recently. */
export async function readRootCoverage(rootDir) {
    const dir = resolve(rootDir);
    const found = (await Promise.all([
        readCandidate(dir, 'coverage-summary', join(dir, 'coverage', 'coverage-summary.json')),
        readCandidate(dir, 'lcov', join(dir, 'coverage', 'lcov.info')),
        readCandidate(dir, 'snapshot', join(dir, SNAPSHOT_FILE)),
    ])).filter(Boolean);

    if (!found.length) return null;
    found.sort((a, b) => b.ts - a.ts);
    return found[0];
}

// ── Config discovery (mirrors sloc.js) ───────────────────────────────────────

async function isRepoRoot(dir) {
    try { await readdir(join(dir, '.git')); return true; } catch { /* not a dir */ }
    try { await readFile(join(dir, '.git'), 'utf-8'); return true; } catch { /* not a gitlink */ }
    return false;
}

async function findCoverageConfig(startDir) {
    let dir = resolve(startDir);
    for (;;) {
        try {
            const data = JSON.parse(await readFile(join(dir, CONFIG_FILE), 'utf-8'));
            if (data && Array.isArray(data.roots)) return { dir, config: data };
        } catch { /* keep looking */ }

        if (await isRepoRoot(dir)) return null; // don't escape the repo
        const parent = dirname(dir);
        if (parent === dir) return null;
        dir = parent;
    }
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Read coverage for the project containing `rootDir`. If a coverage.config.json
 * is found at/above it (within the repo), every declared root is read and the
 * totals are weighted across the roots that have data.
 * @returns {Promise<object>} See RESPONSE SHAPE above.
 */
export async function readCoverage(rootDir, options = {}) {
    const { detail = false, staleAfterDays = DEFAULT_STALE_AFTER_DAYS, useConfig = true } = options;

    const found = useConfig ? await findCoverageConfig(rootDir) : null;
    const base = found ? found.dir : resolve(rootDir);
    const rootSpecs = found
        ? found.config.roots.map((r) => (typeof r === 'string' ? { path: r } : r))
        : [{ path: '.' }];

    const roots = [];
    const totals = emptyTotals();
    const files = {};
    let oldestTs = Infinity;
    const sources = new Set();

    for (const spec of rootSpecs) {
        const dir = join(base, spec.path);
        const report = await readRootCoverage(dir);
        const prefix = (spec.path === '.' || spec.path === '') ? '' : toPosix(spec.path).replace(/\/+$/, '');

        if (!report) {
            roots.push({ path: prefix || '.', available: false, source: null, generatedAt: null, totals: null });
            continue;
        }

        roots.push({
            path: prefix || '.',
            available: true,
            source: report.source,
            generatedAt: report.generatedAt,
            totals: report.totals,
        });

        addTotals(totals, report.totals);
        sources.add(report.source);
        if (report.ts < oldestTs) oldestTs = report.ts;

        if (detail) {
            for (const [p, m] of Object.entries(report.files)) {
                files[prefix ? `${prefix}/${p}` : p] = m;
            }
        }
    }

    const available = roots.some((r) => r.available);
    if (!available) {
        return {
            root: base, available: false, source: null, generatedAt: null,
            ageDays: null, stale: false, totals: emptyTotals(),
            roots, ...(detail ? { files: {} } : {}),
        };
    }

    const ageDays = Math.round(((Date.now() - oldestTs) / 86400000) * 10) / 10;

    return {
        root: base,
        available: true,
        source: sources.size === 1 ? [...sources][0] : 'mixed',
        generatedAt: new Date(oldestTs).toISOString(),
        ageDays,
        stale: ageDays > staleAfterDays,
        totals: finalize(totals),
        roots,
        ...(detail ? { files } : {}),
    };
}

/**
 * Write `.coverage-snapshot.json` for a single package from its LIVE artifact
 * (coverage-summary.json or lcov.info). Never reads an existing snapshot — that
 * would let a stale snapshot perpetuate itself.
 * @returns {Promise<{file: string, source: string, totals: object, fileCount: number}>}
 */
export async function writeSnapshot(rootDir = process.cwd()) {
    const dir = resolve(rootDir);
    const found = (await Promise.all([
        readCandidate(dir, 'coverage-summary', join(dir, 'coverage', 'coverage-summary.json')),
        readCandidate(dir, 'lcov', join(dir, 'coverage', 'lcov.info')),
    ])).filter(Boolean);

    if (!found.length) {
        throw new Error(
            `No coverage artifact in ${dir}. Expected coverage/coverage-summary.json or coverage/lcov.info — run your test:coverage script first.`
        );
    }
    found.sort((a, b) => b.ts - a.ts);
    const best = found[0];

    // Sort paths so the committed file has stable, reviewable diffs.
    const files = {};
    for (const p of Object.keys(best.files).sort()) files[p] = best.files[p];

    const file = join(dir, SNAPSHOT_FILE);
    const payload = {
        version: 1,
        generatedAt: best.generatedAt,
        source: best.source,
        totals: best.totals,
        files,
    };
    await writeFile(file, JSON.stringify(payload, null, 2) + '\n', 'utf-8');
    return { file, source: best.source, totals: best.totals, fileCount: Object.keys(files).length };
}

// ── Endpoint adapters ────────────────────────────────────────────────────────

// Shared cache/compute core behind the Express and Fetch adapters, so /coverage
// behaves identically (same 30s cache) whichever framework wired it up.
function createReportProvider(rootDir, options = {}) {
    const { cacheMs = 30000, name, ...readOptions } = options;
    let cache = null;
    let cachedAt = 0;

    return async function getReport(detail) {
        const now = Date.now();
        if (!detail && cache && now - cachedAt < cacheMs) return cache;

        const report = await readCoverage(rootDir, { ...readOptions, detail });
        const payload = name ? { name, ...report } : report;

        if (!detail) { cache = payload; cachedAt = now; }
        return payload;
    };
}

function wantsDetail(value) { return value === 'true' || value === '1'; }

/** Express handler for `GET /coverage`. */
export function createCoverageRoute(rootDir, options = {}) {
    const getReport = createReportProvider(rootDir, options);
    return async function coverageHandler(req, res) {
        try {
            res.json(await getReport(wantsDetail(req.query?.detail)));
        } catch (err) {
            res.status(500).json({ error: err.message });
        }
    };
}

/** Fetch/SvelteKit handler for `GET /coverage`. */
export function createCoverageHandler(rootDir, options = {}) {
    const getReport = createReportProvider(rootDir, options);
    return async function coverageRequestHandler(event) {
        try {
            const payload = await getReport(wantsDetail(event?.url?.searchParams?.get('detail')));
            return new Response(JSON.stringify(payload), { headers: { 'content-type': 'application/json' } });
        } catch (err) {
            return new Response(JSON.stringify({ error: err.message }), {
                status: 500, headers: { 'content-type': 'application/json' },
            });
        }
    };
}

/**
 * OPTIONAL, not wired by default: spawns `npm run test:coverage`. Running a test
 * suite inside a live server is a production hazard (CPU, real data, external
 * services) — only mount this behind an explicit dev/admin guard.
 */
export function createCoverageRunRoute(options = {}) {
    const { cwd = process.cwd(), script = 'test:coverage' } = options;
    let running = false;

    return async function coverageRunHandler(req, res) {
        if (running) { res.status(409).json({ error: 'Tests already running' }); return; }
        running = true;
        res.status(202).json({ started: true });

        const { spawn } = await import('node:child_process');
        const child = spawn('npm', ['run', script], { cwd, shell: true, stdio: 'inherit' });
        child.on('close', () => { running = false; });
        child.on('error', () => { running = false; });
    };
}

// ── Dashboard ────────────────────────────────────────────────────────────────

function escapeHtml(str) {
    return String(str)
        .replace(/&/g, '&amp;').replace(/</g, '&lt;')
        .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// Exported so a fleet-wide aggregator (process-mgr) can reuse the identical look
// without duplicating the CSS. Thresholds: >=80 good, >=60 warn, else bad.
export const DASHBOARD_STYLE = `
:root {
  --cov-page:#f9f9f7; --cov-surface:#fcfcfb; --cov-text:#0b0b0b; --cov-text-2:#52514e;
  --cov-muted:#898781; --cov-grid:#e1e0d9; --cov-border:rgba(11,11,11,0.10);
  --cov-good:#1baf7a; --cov-warn:#d99a2b; --cov-bad:#d03b3b; --cov-track:#e6e5df;
}
@media (prefers-color-scheme: dark) {
  :root {
    --cov-page:#0d0d0d; --cov-surface:#1a1a19; --cov-text:#fff; --cov-text-2:#c3c2b7;
    --cov-muted:#898781; --cov-grid:#2c2c2a; --cov-border:rgba(255,255,255,0.10);
    --cov-good:#199e70; --cov-warn:#c78a26; --cov-bad:#e66767; --cov-track:#2c2c2a;
  }
}
* { box-sizing: border-box; }
body { margin:0; background:var(--cov-page); color:var(--cov-text); font-family:system-ui,-apple-system,"Segoe UI",sans-serif; }
.cov-page { max-width:960px; margin:0 auto; padding:32px 20px 64px; }
.cov-header { display:flex; justify-content:space-between; align-items:flex-start; gap:16px; margin-bottom:24px; flex-wrap:wrap; }
.cov-header h1 { font-size:20px; margin:0; }
.cov-sub { margin:2px 0 0; color:var(--cov-text-2); font-size:13px; }
.cov-status { color:var(--cov-muted); font-size:12px; }
.cov-btn { font:inherit; font-size:13px; padding:6px 12px; border-radius:6px; border:1px solid var(--cov-border); background:var(--cov-surface); color:var(--cov-text); cursor:pointer; }
.cov-btn:hover { border-color:var(--cov-muted); }
.cov-card { background:var(--cov-surface); border:1px solid var(--cov-border); border-radius:10px; padding:20px; margin-bottom:16px; }
.cov-card-title { font-size:14px; font-weight:600; margin:0 0 12px; }
.cov-hero { text-align:center; padding:32px 20px; }
.cov-hero-value { font-size:56px; font-weight:700; line-height:1.1; }
.cov-hero-label { color:var(--cov-text-2); font-size:14px; margin-top:4px; }
.cov-hero-sub { color:var(--cov-muted); font-size:13px; margin-top:2px; }
.cov-kpis { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; margin-bottom:16px; }
.cov-kpi { background:var(--cov-surface); border:1px solid var(--cov-border); border-radius:10px; padding:14px 16px; }
.cov-kpi-value { font-size:22px; font-weight:600; }
.cov-kpi-label { color:var(--cov-text-2); font-size:12px; margin-top:2px; }
.cov-kpi-sub { color:var(--cov-muted); font-size:11px; margin-top:1px; font-variant-numeric:tabular-nums; }
.cov-bar { height:8px; border-radius:4px; background:var(--cov-track); overflow:hidden; margin-top:8px; }
.cov-bar-fill { height:100%; border-radius:4px; }
.good { color:var(--cov-good); } .warn { color:var(--cov-warn); } .bad { color:var(--cov-bad); }
.bg-good { background:var(--cov-good); } .bg-warn { background:var(--cov-warn); } .bg-bad { background:var(--cov-bad); }
.cov-table-wrap { overflow-x:auto; }
.cov-table { width:100%; border-collapse:collapse; font-size:12px; }
.cov-table th, .cov-table td { padding:6px 10px; border-bottom:1px solid var(--cov-grid); text-align:right; white-space:nowrap; }
.cov-table th.cov-name, .cov-table td.cov-name { text-align:left; }
.cov-table td { font-variant-numeric:tabular-nums; }
.cov-table th { color:var(--cov-text-2); font-weight:600; }
.cov-loading, .cov-error, .cov-empty { text-align:center; color:var(--cov-text-2); padding:48px 16px; }
.cov-error { color:var(--cov-bad); }
.cov-stale { display:inline-block; margin-left:8px; font-size:11px; padding:2px 7px; border-radius:999px; background:rgba(217,154,43,0.15); color:var(--cov-warn); }
.cov-footer { text-align:center; color:var(--cov-muted); font-size:12px; margin-top:24px; }
`;

const DASHBOARD_SCRIPT = `
var COV_DATA_URL = '__DATA_URL__';

function covCls(p) { return p >= 80 ? 'good' : p >= 60 ? 'warn' : 'bad'; }
function covEl(tag, cls, text) {
  var el = document.createElement(tag);
  if (cls) el.className = cls;
  if (text !== undefined) el.textContent = text;
  return el;
}
function covNum(n) { return Number(n).toLocaleString('en-US'); }

function covRenderKpis(totals) {
  var wrap = document.getElementById('cov-kpis');
  wrap.innerHTML = '';
  ['lines', 'statements', 'functions', 'branches'].forEach(function (key) {
    var m = totals[key] || { total: 0, covered: 0, pct: 0 };
    var tile = covEl('div', 'cov-kpi');
    tile.appendChild(covEl('div', 'cov-kpi-value ' + covCls(m.pct), m.pct + '%'));
    tile.appendChild(covEl('div', 'cov-kpi-label', key.charAt(0).toUpperCase() + key.slice(1)));
    tile.appendChild(covEl('div', 'cov-kpi-sub', covNum(m.covered) + ' / ' + covNum(m.total)));
    var bar = covEl('div', 'cov-bar');
    var fill = covEl('div', 'cov-bar-fill bg-' + covCls(m.pct));
    fill.style.width = (m.total > 0 ? m.pct : 0) + '%';
    bar.appendChild(fill);
    tile.appendChild(bar);
    wrap.appendChild(tile);
  });
}

function covRenderRoots(roots) {
  var card = document.getElementById('cov-roots-card');
  if (!roots || roots.length <= 1) { card.hidden = true; return; }
  card.hidden = false;
  var body = document.getElementById('cov-roots');
  body.innerHTML = '';
  var table = covEl('table', 'cov-table');
  var head = covEl('tr');
  ['Package', 'Lines', 'Statements', 'Functions', 'Branches', 'Source'].forEach(function (h, i) {
    head.appendChild(covEl('th', i === 0 ? 'cov-name' : null, h));
  });
  table.appendChild(covEl('thead')).appendChild(head);
  var tbody = covEl('tbody');
  roots.forEach(function (r) {
    var tr = covEl('tr');
    tr.appendChild(covEl('td', 'cov-name', r.path));
    if (!r.available) {
      var td = covEl('td', null, 'no coverage');
      td.colSpan = 5;
      td.style.textAlign = 'right';
      td.style.color = 'var(--cov-muted)';
      tr.appendChild(td);
    } else {
      ['lines', 'statements', 'functions', 'branches'].forEach(function (k) {
        tr.appendChild(covEl('td', covCls(r.totals[k].pct), r.totals[k].pct + '%'));
      });
      tr.appendChild(covEl('td', null, r.source));
    }
    tbody.appendChild(tr);
  });
  table.appendChild(tbody);
  body.appendChild(table);
}

function covRenderFiles(files) {
  var body = document.getElementById('cov-files');
  body.innerHTML = '';
  var rows = Object.keys(files || {}).map(function (p) { return { path: p, m: files[p] }; });
  if (!rows.length) { body.appendChild(covEl('div', 'cov-empty', 'No per-file data.')); return; }
  rows.sort(function (a, b) { return a.m.lines.pct - b.m.lines.pct; });

  var table = covEl('table', 'cov-table');
  var head = covEl('tr');
  ['File', 'Lines', 'Statements', 'Functions', 'Branches'].forEach(function (h, i) {
    head.appendChild(covEl('th', i === 0 ? 'cov-name' : null, h));
  });
  table.appendChild(covEl('thead')).appendChild(head);
  var tbody = covEl('tbody');
  rows.forEach(function (r) {
    var tr = covEl('tr');
    tr.appendChild(covEl('td', 'cov-name', r.path));
    ['lines', 'statements', 'functions', 'branches'].forEach(function (k) {
      var m = r.m[k] || { pct: 0, total: 0 };
      tr.appendChild(covEl('td', m.total > 0 ? covCls(m.pct) : null, m.total > 0 ? m.pct + '%' : '—'));
    });
    tbody.appendChild(tr);
  });
  table.appendChild(tbody);
  body.appendChild(table);
}

function covRender(d) {
  var content = document.getElementById('cov-content');
  var empty = document.getElementById('cov-empty');
  if (!d.available) {
    content.hidden = true; empty.hidden = false;
    return;
  }
  content.hidden = false; empty.hidden = true;

  var lines = d.totals.lines;
  var hero = document.getElementById('cov-hero-value');
  hero.textContent = lines.pct + '%';
  hero.className = 'cov-hero-value ' + covCls(lines.pct);
  document.getElementById('cov-hero-sub').textContent =
    covNum(lines.covered) + ' of ' + covNum(lines.total) + ' lines covered';

  covRenderKpis(d.totals);
  covRenderRoots(d.roots);
  covRenderFiles(d.files);

  var age = d.ageDays === null ? '' : ' · ' + d.ageDays + 'd old';
  var status = document.getElementById('cov-status');
  status.textContent = 'From ' + d.source + age;
  var staleEl = document.getElementById('cov-stale');
  staleEl.hidden = !d.stale;
}

var covLoadingEl = document.getElementById('cov-loading');
var covErrorEl = document.getElementById('cov-error');
var covWrapEl = document.getElementById('cov-content-wrap');

function covLoad() {
  fetch(COV_DATA_URL, { cache: 'no-store' })
    .then(function (res) { if (!res.ok) throw new Error('HTTP ' + res.status); return res.json(); })
    .then(function (d) {
      covLoadingEl.hidden = true; covErrorEl.hidden = true; covWrapEl.hidden = false;
      covRender(d);
    })
    .catch(function (err) {
      covLoadingEl.hidden = true; covWrapEl.hidden = true;
      covErrorEl.hidden = false;
      covErrorEl.textContent = 'Could not load coverage: ' + err.message;
    });
}

document.getElementById('cov-refresh').addEventListener('click', covLoad);
covLoad();
`;

function renderDashboardHtml(name, dataUrl) {
    const safeName = escapeHtml(name);
    const safeDataUrl = escapeHtml(dataUrl);
    const script = DASHBOARD_SCRIPT.replace('__DATA_URL__', dataUrl.replace(/'/g, "\\'"));

    return '<!doctype html>\n<html lang="en">\n<head>\n'
        + '<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        + '<title>Coverage — ' + safeName + '</title>\n'
        + '<style>' + DASHBOARD_STYLE + '</style>\n'
        + '</head>\n<body>\n<div class="cov-page">\n'
        + '  <header class="cov-header">\n'
        + '    <div>\n      <h1>' + safeName + '<span id="cov-stale" class="cov-stale" hidden>stale</span></h1>\n'
        + '      <p class="cov-sub">Test coverage</p>\n    </div>\n'
        + '    <div style="display:flex;align-items:center;gap:12px">\n'
        + '      <span id="cov-status" class="cov-status">Loading…</span>\n'
        + '      <button id="cov-refresh" class="cov-btn" type="button">Refresh</button>\n'
        + '    </div>\n  </header>\n'
        + '  <main aria-live="polite">\n'
        + '    <div id="cov-loading" class="cov-loading">Loading coverage…</div>\n'
        + '    <div id="cov-error" class="cov-error" hidden></div>\n'
        + '    <div id="cov-empty" class="cov-empty" hidden>No coverage data. Run <code>npm run test:coverage</code>, then commit <code>' + SNAPSHOT_FILE + '</code>.</div>\n'
        + '    <div id="cov-content-wrap" hidden>\n      <div id="cov-content">\n'
        + '        <section class="cov-card cov-hero">\n'
        + '          <div class="cov-hero-value" id="cov-hero-value">—</div>\n'
        + '          <div class="cov-hero-label">line coverage</div>\n'
        + '          <div class="cov-hero-sub" id="cov-hero-sub"></div>\n'
        + '        </section>\n'
        + '        <section class="cov-kpis" id="cov-kpis"></section>\n'
        + '        <section class="cov-card" id="cov-roots-card" hidden>\n'
        + '          <h2 class="cov-card-title">By package</h2>\n'
        + '          <div id="cov-roots" class="cov-table-wrap"></div>\n'
        + '        </section>\n'
        + '        <section class="cov-card">\n'
        + '          <h2 class="cov-card-title">By file — least covered first</h2>\n'
        + '          <div id="cov-files" class="cov-table-wrap"></div>\n'
        + '        </section>\n'
        + '      </div>\n    </div>\n  </main>\n'
        + '  <footer class="cov-footer">Served by coverage.js · data from GET ' + safeDataUrl
        + ' · lcov reports no statements (aliased to lines)</footer>\n'
        + '</div>\n<script>' + script + '</script>\n</body>\n</html>\n';
}

/** Express handler serving the self-contained `/coverage/dashboard` page. */
export function createCoverageDashboardRoute(options = {}) {
    const { name = 'app', dataUrl = '/coverage?detail=true' } = options;
    const html = renderDashboardHtml(name, dataUrl);
    return function coverageDashboardHandler(req, res) {
        res.type('html').send(html);
    };
}

/** Fetch/SvelteKit equivalent of createCoverageDashboardRoute. */
export function createCoverageDashboardHandler(options = {}) {
    const { name = 'app', dataUrl = '/coverage?detail=true' } = options;
    const html = renderDashboardHtml(name, dataUrl);
    return function coverageDashboardRequestHandler() {
        return new Response(html, { headers: { 'content-type': 'text/html' } });
    };
}

// ── CLI ──────────────────────────────────────────────────────────────────────
//   node coverage.js --ensure-dir   create ./coverage (node:test won't, and
//                                   `mkdir -p` isn't portable to Windows cmd)
//   node coverage.js --snapshot     write ./.coverage-snapshot.json
//
// Paths are anchored on process.cwd(), so `node ../coverage.js --snapshot` run
// from a sub-package acts on THAT package.

const invokedDirectly = typeof process !== 'undefined'
    && Array.isArray(process.argv)
    && /(^|[\\/])coverage\.js$/.test(process.argv[1] ?? '');

if (invokedDirectly && process.argv.includes('--ensure-dir')) {
    await mkdir(join(process.cwd(), 'coverage'), { recursive: true });
}

if (invokedDirectly && process.argv.includes('--snapshot')) {
    try {
        const result = await writeSnapshot(process.cwd());
        const l = result.totals.lines;
        console.log(
            `coverage: wrote ${SNAPSHOT_FILE} from ${result.source} — `
            + `${l.pct}% lines (${l.covered}/${l.total}) across ${result.fileCount} files`
        );
    } catch (err) {
        console.error(`coverage: ${err.message}`);
        process.exitCode = 1;
    }
}
