const { withAndroidManifest } = require('@expo/config-plugins')

// This app's whole backend (the SvelteKit gateway on the LAN/Tailscale host + relay-server) is
// plain HTTP, no TLS — matching PLAN.md's "Single gateway, no relay changes" decision (traffic
// never leaves the LAN/Tailscale tunnel, so no cert was ever provisioned). Android blocks all
// cleartext (non-HTTPS) traffic by default since API 28 (targetSdk 28+), so without this every
// fetch() to the configured API host would fail with a network security exception on a real
// device — this isn't optional for this app's actual traffic pattern.
//
// A config PLUGIN (not a one-off hand-edit of the generated android/app/src/main/
// AndroidManifest.xml) because that file is regenerated by `expo prebuild` — a manual edit would
// silently vanish on the next clean prebuild/EAS build.
module.exports = function withCleartextTraffic(config) {
    return withAndroidManifest(config, (config) => {
        const app = config.modResults.manifest.application?.[0]
        if (app) app.$['android:usesCleartextTraffic'] = 'true'
        return config
    })
}
